ALTER TABLE "notes"
ADD COLUMN "title" TEXT NOT NULL DEFAULT '',
ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "body_plaintext" TEXT,
ALTER COLUMN "ciphertext" DROP NOT NULL,
ALTER COLUMN "iv" DROP NOT NULL,
ALTER COLUMN "aad" DROP NOT NULL;
